### PR TITLE
feat: extend GraphQL schema with StatsContainer, Transaction and TransferEvent entities

### PR DESCRIPTION
**Pull request by niklr**
I wish I had found your subgraph earlier. It made me realize how powerful The Graph actually is and would be a perfect fit for #1 and #9 to fetch the data. There is something new to learn everyday as I'm still very fresh to the blockchain ecosystem. :)

With this PR I would like to extend the GraphQL schema with the following entities:

- StatsContainer (keep track of all indexes for pagination purposes)
- Transaction (enable use cases to query block transactions directly)
- TransferEvents (enable use cases to query events of type transfer directly)

Current pagination options are rather limited:

- The `first` argument must be between 0 and 1000
- The `skip` argument must be between 0 and 5000

### CODE REVIEW

**Comment by QYuQianchen** [comment]
Hi @niklr Thanks for the PR and proposal to the new feature. Could you please explain to me why `Transactions` and `Transfer` events are necessary ? Is there anything that cannot be achieved by querying [RPC endpoint](https://www.xdaichain.com/for-developers/developer-resources#json-rpc-endpoints)?

**Comment by niklr** [comment]
Hi @QYuQianchen. While trying to fetch the data needed to build a network graph for #9 I encountered several problems. As far as I know it is not possible to get a list of `Transactions` for a specific token/contract by querying the RPC endpoint. So basically the only option is getting all `Transfer` events first. Unfortunately, events only contain the `blockNumber` and n calls to `getBlock(blockNumber)` would be needed in order to get the timestamps. (which was a requirement: The amount of tokens being transferred and the timestamp of the transfer is labeled on the edge.)

Another requirement was to build a combined graph of both Ethereum and xDAI chains, as if no bridge existed. I think this can be achieved by getting `TokensBridged` and `TokensBridgingInitiated` events issued by the respective bridge contracts. Then the `messageId` could be used to associate a `Mint` event on xDai (from 0x to recipient) with a `Transfer` event (from sender to bridge) on ETH and finally to project it as a transfer from sender to recipient.

Querying for such a use case would be a breeze by having `Transaction` entities with a nested list of events (`Transfer` + `TokensBridged` and `TokensBridgingInitiated`) on TheGraph for botch chains.

**Review by QYuQianchen — APPROVED** [review]
LGTM

**Comment by QYuQianchen** [comment]
Subgraph is updated: https://thegraph.com/explorer/subgraph/hoprnet/hopr-on-xdai

**Pull request merged**
